name: CI - Validation HTML

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Logs - afficher les fichiers
        run: |
          echo "Fichiers du projet :"
          ls -la

      - name: Test - Validation du HTML
        run: |
          npm init -y >/dev/null 2>&1
          npm install -D html-validate >/dev/null 2>&1
          npx html-validate index.html

      - name: Build - Créer l’artefact
        run: |
          mkdir -p dist
          cp index.html dist/
          echo "Artefact créé dans dist/"

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-statique
          path: dist
